/**
 * Additional built-in catalog rows — variations, machines, gymnastics,
 * kettlebell, sled, and accessory work. Merged in movement-catalog.ts.
 */
import type { CatalogDraft, MovementLevel } from './movement-catalog-types';

function e(
  code: string,
  name: string,
  category: string,
  equipment: string,
  muscles: string,
  level: MovementLevel,
  overview: string,
  details: string
): CatalogDraft {
  return { code, name, category, equipment, muscles, level, overview, details };
}

export const SYSTEM_MOVEMENT_CATALOG_EXTRA: CatalogDraft[] = [
  // ── Squat variations ───────────────────────────────────
  e('SYS_MOV_AIR_SQUAT', 'Air squat', 'Squat', 'Bodyweight', 'Quads, glutes', 'beginner',
    'Unloaded squat to full depth. The teaching pattern for every loaded squat.',
    'Feet about shoulder-width, sit between the hips, chest tall, heels down. Hit below parallel if the back stays long. Use as a warm-up, a class standard, or high-rep conditioner. If heels lift, shorten depth or elevate them slightly.'),
  e('SYS_MOV_PAUSE_SQUAT', 'Pause squat', 'Squat', 'Barbell, rack', 'Quads, glutes, core', 'intermediate',
    'Squat with a dead-stop in the hole. Builds strength out of the bottom and kills bounce.',
    'Same setup as a back or front squat. Sit, hold 1–3 seconds without relaxing the brace, then stand. No rocking. Use 60–80% of a normal squat. Excellent for lifters who bounce or lose position at depth.'),
  e('SYS_MOV_TEMPO_SQUAT', 'Tempo squat', 'Squat', 'Barbell or goblet', 'Quads, glutes, core', 'intermediate',
    'Squat with a prescribed eccentric (e.g. 3-1-1). Time under tension and control.',
    'Write the tempo on the board (down-pause-up). Do not rush the lowering. Lighten the load. Great teaching tool and hypertrophy work. Stop the set when the tempo breaks.'),
  e('SYS_MOV_PIN_SQUAT', 'Pin squat', 'Squat', 'Barbell, rack pins', 'Quads, glutes', 'intermediate',
    'Squat to pins and pause, then press off a dead stop. Overload the hole safely.',
    'Set pins at or just above target depth. Sit the bar onto the pins, settle, then stand without bouncing. Spotters still useful. Teaches tightness at the bottom. Not a max-effort circus lift.'),
  e('SYS_MOV_ZERCHER_SQUAT', 'Zercher squat', 'Squat', 'Barbell', 'Quads, glutes, upper back, core', 'intermediate',
    'Bar in the crook of the elbows. Upright torso and brutal trunk work.',
    'Cradle the bar in the elbows, hug it in, sit down with a tall chest. Pad the arms if needed. Excellent for people who cannot front-rack. Keep the elbows from dumping. Moderate loads go a long way.'),
  e('SYS_MOV_SSB_SQUAT', 'Safety-bar squat', 'Squat', 'Safety squat bar, rack', 'Quads, glutes, upper back', 'intermediate',
    'Cambered yoke bar on the back. Easier on the shoulders, harder on the upper back.',
    'Handles in front, sit down as in a high-bar squat. The bar wants to tip you forward — fight with a tall chest. Great when shoulders cannot back-rack. Treat the load as a bit heavier than it looks.'),
  e('SYS_MOV_BELT_SQUAT', 'Belt squat', 'Squat', 'Belt-squat machine or landmine belt', 'Quads, glutes', 'beginner',
    'Load hanging from a hip belt. Squat pattern with almost no spinal compression.',
    'Stand on the platform, belt snug, sit down and stand. Keep the torso upright. Ideal when the back is fried or for high-volume quad work. Do not turn it into a good-morning.'),
  e('SYS_MOV_HACK_SQUAT', 'Hack squat (machine)', 'Squat', 'Hack-squat machine', 'Quads, glutes', 'beginner',
    'Machine squat on a fixed path. High quad bias, simple to load.',
    'Back and hips on the pads, feet mid-platform. Lower under control, do not bounce the sled. Higher feet = more glute; lower = more quad. Keep the low back from tucking at the bottom.'),
  e('SYS_MOV_PENDULUM_SQUAT', 'Pendulum squat', 'Squat', 'Pendulum-squat machine', 'Quads, glutes', 'beginner',
    'Arcing machine squat. Long quad range with a supported torso.',
    'Shoulders under the pads, ride the arc to depth, stand without locking harshly. A hypertrophy favourite. Control the eccentric. Not every gym has one — leg press is the stand-in.'),
  e('SYS_MOV_SISSY_SQUAT', 'Sissy squat', 'Squat', 'Bodyweight or sissy pad', 'Quads', 'intermediate',
    'Knee-travel squat that lights up the quads. Advanced knee-dominant isolation.',
    'Hold a rack, lean back as the knees travel forward, heels may lift. Only as far as the knees allow. Slow. Not for irritable patellar tendons. A lean-back wall squat is a friendlier cousin.'),
  e('SYS_MOV_PISTOL', 'Pistol squat', 'Squat', 'Bodyweight, box to scale', 'Quads, glutes, balance', 'advanced',
    'Single-leg squat to full depth. Strength, mobility, and balance in one.',
    'Stand on one leg, other leg long, sit to depth and stand. Scale to a box, a TRX, or a counterweight. Do not collapse the knee inward. Most members should box-pistol first.'),
  e('SYS_MOV_SHRIMP', 'Shrimp squat', 'Squat', 'Bodyweight', 'Quads, glutes', 'advanced',
    'Rear-foot-held single-leg squat. Harder than it looks; huge quad demand.',
    'Hold the rear foot, sit the back knee toward the floor, stand. Use a bench or rack assist. Short range first. Skip if the knee or the rear hip complains.'),
  e('SYS_MOV_COSSACK_SQUAT', 'Cossack squat', 'Squat', 'Bodyweight or kettlebell', 'Adductors, quads, glutes', 'intermediate',
    'Deep side squat. Frontal-plane strength and adductor length.',
    'Wide stance, sit into one hip, other leg long with the toes up if mobile. Alternate. Goblet hold helps the chest stay tall. Do not force the bottom if the hip pinches — raise the range.'),
  e('SYS_MOV_WALL_SIT', 'Wall sit', 'Squat', 'Wall', 'Quads, glutes', 'beginner',
    'Isometric squat against a wall. Simple quad burn and a class finisher.',
    'Back on the wall, thighs parallel, knees over mid-foot. Breathe. 20–60 seconds. A plate on the thighs or a calf-raise at the bottom are optional spices. Stop if the knees scream.'),
  e('SYS_MOV_LANDMINE_SQUAT', 'Landmine squat', 'Squat', 'Barbell in landmine', 'Quads, glutes, core', 'beginner',
    'Goblet-style squat holding a landmine. Friendly path and easy to load.',
    'Hold the sleeve at the chest, sit down and stand. The arc keeps people upright. Great for new members and for high-rep finishers. Do not turn it into a good-morning.'),
  e('SYS_MOV_KB_FRONT_SQUAT', 'Double kettlebell front squat', 'Squat', 'Two kettlebells', 'Quads, glutes, upper back', 'intermediate',
    'Two bells in the rack. Front-squat stimulus without a barbell.',
    'Clean the bells, elbows up, sit down. The rack will humble the upper back. Moderate loads, quality reps. If the bells dump, reset the rack before the next rep.'),
  e('SYS_MOV_SMITH_SQUAT', 'Smith-machine squat', 'Squat', 'Smith machine', 'Quads, glutes', 'beginner',
    'Fixed-path squat. Useful when free-bar skill is not there yet, or for isolation volume.',
    'Set the feet so the knees track well — often slightly forward of the bar. Unrack, sit, stand, re-rack the hooks. Do not treat it like a free squat for 1RMs. Control both directions.'),
  e('SYS_MOV_HEEL_SQUAT', 'Heels-elevated squat', 'Squat', 'Plates or wedge, goblet or bar', 'Quads', 'beginner',
    'Squat with heels on plates. More knee travel and quad, less ankle demand.',
    'Small plates under the heels, sit tall between the knees. A teaching tool and a quad builder. Do not use it as the only squat forever — still train the ankle.'),
  e('SYS_MOV_CYCLIST_SQUAT', 'Cyclist squat', 'Squat', 'Wedge, dumbbell or smith', 'Quads', 'intermediate',
    'Narrow stance, high heels. Extreme knee-dominant quad work.',
    'Feet close, heels high, torso upright, sit straight down. Light to moderate. Slow eccentrics. Not a max-strength lift. Skip if the knees are irritable.'),
  e('SYS_MOV_ANDERSON_SQUAT', 'Anderson squat', 'Squat', 'Barbell, low pins', 'Quads, glutes', 'advanced',
    'Start each rep from pins in the hole. Concentric-only squat strength.',
    'Set the bar on pins at depth, get under it tight, and stand. Reset every rep. Brutal and specific. Use after a normal squat pattern is solid.'),

  // ── Hinge variations ───────────────────────────────────
  e('SYS_MOV_TRAP_BAR_DL', 'Trap-bar deadlift', 'Hinge', 'Trap / hex bar', 'Quads, glutes, hamstrings, erectors', 'beginner',
    'Deadlift inside a hex bar. More squat-deadlift hybrid and easier to teach than a straight bar.',
    'Stand in the middle, high or low handles, brace, stand tall. High handles are the friendliest first pull. Do not hyperextend at the top. A staple for athletes and new members.'),
  e('SYS_MOV_SL_RDL', 'Single-leg Romanian deadlift', 'Hinge', 'Dumbbell or kettlebell', 'Hamstrings, glutes, balance', 'intermediate',
    'One-leg hinge. Posterior chain plus hip stability.',
    'Soft knee, hips square, reach the free leg back as a counterweight. Touch the bell to mid-shin and stand. Hold a rack if balance fails. Do not rotate the pelvis open.'),
  e('SYS_MOV_BSTANCE_RDL', 'B-stance RDL', 'Hinge', 'Dumbbells or barbell', 'Hamstrings, glutes', 'beginner',
    'Staggered-stance RDL. Almost single-leg without the balance circus.',
    'Kickstand the back foot on the toe, hinge on the front hip. Most of the load is on the front leg. Easier to load than a true SL RDL. Great accessory.'),
  e('SYS_MOV_STIFF_DL', 'Stiff-leg deadlift', 'Hinge', 'Barbell', 'Hamstrings, erectors', 'intermediate',
    'Hinge with nearly straight knees. More hamstring and more back than an RDL.',
    'Softer than locked, but less knee bend than an RDL. Bar close, spine long. Shorten the range if the back rounds. Not a bounce off the floor unless you meant a conventional pull.'),
  e('SYS_MOV_DEFICIT_DL', 'Deficit deadlift', 'Hinge', 'Barbell, plates to stand on', 'Hamstrings, glutes, erectors', 'advanced',
    'Deadlift from a small rise. Longer range and a harder start.',
    'Stand on 2–5 cm plates, same conventional setup. Only if the floor pull is already clean. Easy to turn into a rounded-back mess — film it. Lighten the load.'),
  e('SYS_MOV_RACK_PULL', 'Rack pull', 'Hinge', 'Barbell, rack pins', 'Glutes, erectors, traps, grip', 'intermediate',
    'Deadlift from pins above the floor. Overload the lockout and the upper back.',
    'Set pins at mid-shin or just below the knee. Brace and stand. Do not bounce the bar on the pins. A volume tool, not a substitute for a full pull.'),
  e('SYS_MOV_BLOCK_PULL', 'Block pull', 'Hinge', 'Barbell, blocks', 'Glutes, erectors, hamstrings', 'intermediate',
    'Deadlift from blocks. Same idea as a rack pull with a more natural bar path.',
    'Bar starts on blocks at the chosen height. Set, brace, stand. Useful when the gym has no pins or for sumo lockout work.'),
  e('SYS_MOV_SNATCH_DL', 'Snatch-grip deadlift', 'Hinge', 'Barbell', 'Hamstrings, back, grip', 'advanced',
    'Wide-grip deadlift. Longer range and a savage upper-back builder.',
    'Snatch grip, same hinge rules. Straps are honest here. Only if the back stays long. A special-strength tool, not a beginner pull.'),
  e('SYS_MOV_KB_DL', 'Kettlebell deadlift', 'Hinge', 'Kettlebell', 'Glutes, hamstrings, lats', 'beginner',
    'First hinge off the floor. The right first deadlift for most members.',
    'Bell between the feet, hinge, grip, stand tall. Repeat. Two bells or a heavier single next. Teach this before a barbell. Keep the chest proud and the back long.'),
  e('SYS_MOV_CABLE_PULL_THRU', 'Cable pull-through', 'Hinge', 'Cable, rope', 'Glutes, hamstrings', 'beginner',
    'Hinge facing away from a low cable. Easy glute-ham pattern with constant tension.',
    'Straddle the rope, walk out, hinge until the hamstrings load, then snap the hips. Do not squat it. A warm-up or a high-rep finisher. Face away so the cable pulls you into the hinge.'),
  e('SYS_MOV_BACK_EXT', '45-degree back extension', 'Hinge', '45-degree hyper bench', 'Erectors, glutes, hamstrings', 'beginner',
    'Hip hinge on a 45° bench. Posterior-chain volume without a heavy bar.',
    'Pad at the hip crease, hinge until you feel the hamstrings, then squeeze back to a straight line — not a backbend. Hold a plate at the chest to load. Round-back variations are advanced and optional.'),
  e('SYS_MOV_REV_HYPER', 'Reverse hyper', 'Hinge', 'Reverse-hyper machine', 'Glutes, hamstrings, erectors', 'intermediate',
    'Hips extend the legs against a pendulum. Famous for backs that are tired, not injured.',
    'Torso on the pad, swing the legs to a squeeze, control back. Do not yank into hyperextension. If the gym has no machine, a 45° hyper is the stand-in.'),
  e('SYS_MOV_GHD_HIP', 'GHD hip extension', 'Hinge', 'GHD', 'Glutes, hamstrings', 'intermediate',
    'Hip extension on a glute-ham developer. Posterior chain with a long lever.',
    'Hips just off the pad, hinge and come back to a straight body. Not a sit-up. Control the lower. GHD sit-ups are a different movement — do not mix the names on the whiteboard.'),
  e('SYS_MOV_SL_HIP_THRUST', 'Single-leg hip thrust', 'Hinge', 'Bench, bodyweight or dumbbell', 'Glutes, hamstrings', 'intermediate',
    'One-leg hip thrust. High glute tension, little axial load.',
    'Upper back on a bench, one foot planted, other leg long or bent. Drive to a full lockout, pause. Hips stay level. Bodyweight is enough for a long time.'),
  e('SYS_MOV_FROG_PUMP', 'Frog pump', 'Hinge', 'Floor, optional dumbbell', 'Glutes', 'beginner',
    'Bridge with soles together. Short-range glute pump and activation.',
    'Lie on the back, soles of the feet together, knees out. Pulse or pause at the top. High reps. A warm-up, not a main lift. Keep the ribs down.'),
  e('SYS_MOV_AM_SWING', 'American kettlebell swing', 'Hinge', 'Kettlebell', 'Glutes, lats, shoulders, core', 'intermediate',
    'Swing all the way overhead. More shoulder and midline than a Russian swing.',
    'Same hike and hip snap, finish with the bell stacked over the head. Only if the overhead position is clean. Many gyms prefer Russian (chest height) for general fitness. Do not squat the swing.'),
  e('SYS_MOV_SA_SWING', 'Single-arm kettlebell swing', 'Hinge', 'Kettlebell', 'Glutes, core, grip', 'intermediate',
    'One-arm swing. Anti-rotation on top of the hinge.',
    'Same hip snap, one hand. Do not let the torso twist. Switch hands every 5–10 or mid-air if they have the skill. Lighter than the two-hand swing.'),
  e('SYS_MOV_SUITCASE_DL', 'Suitcase deadlift', 'Hinge', 'Dumbbell or kettlebell', 'Obliques, glutes, grip', 'beginner',
    'One-sided deadlift. Hinge plus anti-side-bend.',
    'Bell outside one foot, hinge and stand tall as if both hands were loaded. Do not lean. Alternate sides. A great first “odd-object” pull.'),

  // ── Lunge / split ──────────────────────────────────────
  e('SYS_MOV_FWD_LUNGE', 'Forward lunge', 'Lunge', 'Bodyweight or dumbbells', 'Quads, glutes', 'beginner',
    'Step forward into a split squat and return. More deceleration than a reverse lunge.',
    'Step long enough that the front shin is roughly vertical, back knee toward the floor, then push back. Softer on some knees to reverse-lunge instead. Do not slam the front heel.'),
  e('SYS_MOV_CURTSY_LUNGE', 'Curtsy lunge', 'Lunge', 'Bodyweight or dumbbells', 'Glutes, abductors, quads', 'beginner',
    'Rear leg crosses behind. Hits the glute med and a different hip angle.',
    'Step the back foot behind and outside the front heel, sit, stand. Keep the pelvis from rotating wildly. A light goblet is plenty. Skip if the front knee caves.'),
  e('SYS_MOV_STATIC_SPLIT', 'Static split squat', 'Lunge', 'Bodyweight or dumbbells', 'Quads, glutes', 'beginner',
    'Split stance, no step. The cleanest way to load one leg first.',
    'Long stance, drop straight down, stand. Stay on one side for all reps. Easier to coach than walking lunges. Elevate the front or rear foot to change the bias.'),
  e('SYS_MOV_FFE_SPLIT', 'Front-foot elevated split squat', 'Lunge', 'Plate or low box, dumbbells', 'Quads, glutes', 'intermediate',
    'Split squat with the front foot on a plate. More range and more stretch on the rear hip.',
    'Front foot on 5–10 cm, drop the back knee, stand. A cousin of the Bulgarian that is often kinder. Control the bottom. Tall torso.'),
  e('SYS_MOV_DEF_REV_LUNGE', 'Deficit reverse lunge', 'Lunge', 'Low box, dumbbells', 'Quads, glutes', 'intermediate',
    'Reverse lunge off a small step. Longer range on the front leg.',
    'Stand on a plate or low box, step back to the floor, then drive up. Do not crash. Moderate load. Excellent single-leg volume after squats.'),
  e('SYS_MOV_LAT_STEP_UP', 'Lateral step-up', 'Lunge', 'Box', 'Glutes, quads, abductors', 'beginner',
    'Step onto a box from the side. Frontal-plane single-leg work.',
    'Stand beside the box, step up, stand tall, lower with control. Do not push off the trailing foot. Box height mid-shin for most people.'),
  e('SYS_MOV_JUMP_LUNGE', 'Jumping lunge', 'Lunge', 'Bodyweight', 'Quads, glutes, calves', 'intermediate',
    'Split-squat jump, switch legs in the air. Power and conditioning.',
    'Soft landings, quiet feet, upright torso. Short sets. Step-back lunges if the landings get sloppy. Not a beginner first lunge.'),
  e('SYS_MOV_TRX_LUNGE', 'TRX / suspended lunge', 'Lunge', 'TRX or rings', 'Quads, glutes', 'intermediate',
    'Rear foot in a strap. Bulgarian-style without a bench.',
    'Foot in the cradle, drop and stand. The strap moves — that is the point. Hold the handles only if balance fails. Slow.'),
  e('SYS_MOV_CLOCK_LUNGE', 'Clock lunge', 'Lunge', 'Bodyweight', 'Quads, glutes, adductors', 'beginner',
    'Lunges around the clock — forward, diagonal, side, back. Warm-up and prep.',
    'Same standing foot, step to 12, 1:30, 3, 4:30, 6. Then the other side. Bodyweight. A mobility-strength hybrid, not a heavy day.'),

  // ── Push variations ────────────────────────────────────
  e('SYS_MOV_CG_BENCH', 'Close-grip bench press', 'Push', 'Barbell, bench', 'Triceps, pecs, anterior delts', 'intermediate',
    'Narrower bench. More triceps, still a press.',
    'Hands just inside shoulder-width — not a hands-together circus. Elbows closer to the torso. Lower to the lower chest. A press accessory, not a skull-crusher.'),
  e('SYS_MOV_PAUSE_BENCH', 'Pause bench press', 'Push', 'Barbell, bench', 'Pecs, triceps, delts', 'intermediate',
    'Dead-stop on the chest. Builds raw pressing strength and control.',
    'Lower, sit on the chest 1–2 seconds without relaxing the upper back, then press. No bounce. Lighten the load. Competition-style if they lift that way.'),
  e('SYS_MOV_DB_BENCH', 'Dumbbell bench press', 'Push', 'Dumbbells, bench', 'Pecs, triceps, delts', 'beginner',
    'DB flat press. More range and more shoulder freedom than a bar.',
    'Bells over the chest, lower with the elbows about 45–70°, press and squeeze. Do not crash the bells together. A spotter still helps getting into position when they are heavy.'),
  e('SYS_MOV_DB_INCLINE', 'Dumbbell incline press', 'Push', 'Dumbbells, incline bench', 'Upper pecs, delts, triceps', 'beginner',
    'Incline press with bells. Friendlier path than a barbell for many shoulders.',
    '15–30° is enough. Lower under control, press up and slightly in. Do not turn a 60° bench into a shoulder press and call it chest.'),
  e('SYS_MOV_FLOOR_PRESS', 'Floor press', 'Push', 'Barbell or dumbbells', 'Triceps, pecs', 'intermediate',
    'Press from the floor. Shorter range, huge lockout and triceps.',
    'Lie on the floor, lower until the triceps touch, pause, press. No leg drive. Great when the shoulders dislike a full bench or as a lockout builder.'),
  e('SYS_MOV_MACHINE_CHEST', 'Machine chest press', 'Push', 'Chest-press machine', 'Pecs, triceps, delts', 'beginner',
    'Seated machine press. Simple loading for new members and high-rep work.',
    'Seat so the handles meet mid-chest. Press without shrugging. Do not slam the stack. A valid main press when free weights are not the session.'),
  e('SYS_MOV_PEC_DECK', 'Pec deck / machine fly', 'Push', 'Pec-deck machine', 'Pectorals', 'beginner',
    'Machine fly. Isolation for the chest with a fixed path.',
    'Elbows soft, hug the pads together, control the open. Do not overstretch the front of the shoulder. A finisher, not a first press.'),
  e('SYS_MOV_CABLE_FLY', 'Cable fly', 'Push', 'Dual cables', 'Pectorals', 'beginner',
    'Standing or bench cable fly. Constant tension across the chest.',
    'Slight elbow bend, bring the hands together in a hug, return to a stretch you can control. High, mid, or low pulleys change the line. Light enough to feel the pec, not the front delt.'),
  e('SYS_MOV_DB_FLY', 'Dumbbell fly', 'Push', 'Dumbbells, bench', 'Pectorals', 'intermediate',
    'Open the arms on a bench. Stretch-focused chest work — easy to overdo.',
    'Soft elbows, lower only as far as the shoulder likes, hug back up. This is not a pullover and not a press. Light bells. Stop if the front shoulder nips.'),
  e('SYS_MOV_DECLINE_BENCH', 'Decline bench press', 'Push', 'Barbell or dumbbells, decline bench', 'Lower pecs, triceps', 'intermediate',
    'Press on a decline. More lower-chest, less shoulder flexion.',
    'Secure the legs, unrack carefully, lower to the lower chest, press. Not essential if they already bench and dip. Spotters matter on a decline.'),
  e('SYS_MOV_PIKE_PUSH', 'Pike push-up', 'Push', 'Bodyweight', 'Delts, triceps, upper pecs', 'intermediate',
    'Hips high push-up. The first step toward a handstand push-up.',
    'Downward-dog shape, lower the head in front of the hands, press. Elevate the feet to make it harder. Forehead to a mat, not the neck. Scale with a box pike.'),
  e('SYS_MOV_HSPU', 'Handstand push-up', 'Push', 'Wall, mats', 'Delts, triceps, traps', 'advanced',
    'Inverted press. High skill, high shoulder demand.',
    'Kick up to a wall, lower the head to a mat or deficit, press. Strict first, kipping only if the session says so. Box pike and seated DB press are the honest scales. Warm the shoulders.'),
  e('SYS_MOV_DIAMOND_PU', 'Diamond push-up', 'Push', 'Bodyweight', 'Triceps, pecs', 'intermediate',
    'Hands close under the chest. Triceps-biased push-up.',
    'Thumbs and index fingers close (they need not touch). Elbows toward the body. Knee or bench scale if they collapse. Full range.'),
  e('SYS_MOV_DEFICIT_PU', 'Deficit push-up', 'Push', 'Parallettes or plates', 'Pecs, triceps, core', 'intermediate',
    'Push-up with the hands raised. Extra range at the bottom.',
    'Hands on parallettes or plates, chest below the hands, press. Only as deep as the shoulders allow. A strong chest builder when regular push-ups are easy.'),
  e('SYS_MOV_DECLINE_PU', 'Decline push-up', 'Push', 'Box', 'Upper pecs, delts, triceps', 'intermediate',
    'Feet elevated push-up. More shoulder and upper chest.',
    'Feet on a box, body straight, full range. The higher the box, the more it becomes a pike. Keep the plank.'),
  e('SYS_MOV_Z_PRESS', 'Z-press', 'Push', 'Barbell or dumbbells, floor', 'Delts, triceps, core', 'advanced',
    'Seated-on-the-floor overhead press. No leg drive, nowhere to hide the midline.',
    'Sit tall with the legs straight, press from the shoulders. If they cannot sit tall, they are not ready — raise the hips on a plate or go back to a strict press. Light.'),
  e('SYS_MOV_LANDMINE_PRESS', 'Landmine press', 'Push', 'Barbell in landmine', 'Delts, pecs, triceps, core', 'beginner',
    'Press along an arc. Shoulder-friendly vertical/horizontal hybrid.',
    'Half-kneeling or standing, press the sleeve up and forward. Single-arm is the usual. Do not shrug into the ear. A staple when overhead is spicy.'),
  e('SYS_MOV_SA_LANDMINE', 'Single-arm landmine press', 'Push', 'Barbell in landmine', 'Delts, core, pecs', 'beginner',
    'One-arm landmine press. Anti-rotation plus a friendly press path.',
    'Opposite knee down (half-kneeling) is the coaching default. Press without rotating the ribs. Switch sides. Great for return-to-press work.'),
  e('SYS_MOV_ARNOLD', 'Arnold press', 'Push', 'Dumbbells', 'Delts, triceps', 'intermediate',
    'Rotate from palms-in at the bottom to palms-forward at the top. All three delts get a say.',
    'Start at the shoulders, palms facing you, rotate as you press. Control the lower. Moderate load. Not a first overhead for new members.'),
  e('SYS_MOV_JM_PRESS', 'JM press', 'Push', 'Barbell, bench', 'Triceps, pecs', 'advanced',
    'Hybrid of a close-grip bench and a skull crusher. Serious triceps.',
    'Lower the bar toward the upper chest / throat with the elbows high, then press. Learn it with an empty bar. Not a class-wide standard unless the coach can teach it.'),
  e('SYS_MOV_RING_DIP', 'Ring dip', 'Push', 'Gymnastic rings', 'Pecs, triceps, core', 'advanced',
    'Dip on rings. Unstable and much harder than bar dips.',
    'Support with rings turned out at the top, lower under control, press. Scale with a foot assist or a band. Support holds first. Wrists and shoulders must be ready.'),
  e('SYS_MOV_BENCH_DIP', 'Bench dip', 'Push', 'Bench', 'Triceps, anterior delts', 'beginner',
    'Feet-out dip off a bench. Handy, but easy on the front shoulder if you go too deep.',
    'Hands on the bench behind you, lower until the upper arms are about parallel, press. Elevate the feet to load. Stop before the shoulders roll forward. Parallel bars are usually kinder.'),

  // ── Pull variations ────────────────────────────────────
  e('SYS_MOV_PENDLAY', 'Pendlay row', 'Pull', 'Barbell', 'Lats, mid-back, erectors', 'intermediate',
    'Bent-over row from a dead stop on the floor each rep. Strict and explosive.',
    'Hinge to parallel, pull the bar to the lower chest / upper abs, set it down. No bounce. If they cannot hold a flat back, raise the start on blocks or do a chest-supported row.'),
  e('SYS_MOV_YATES_ROW', 'Yates row', 'Pull', 'Barbell', 'Lats, mid-back', 'intermediate',
    'More upright barbell row. Often underhand. Thickness with less hinge demand.',
    'Torso about 45°, pull to the waist. Do not turn it into a shrug-curl. A bodybuilding row, not a Pendlay. Control the eccentric.'),
  e('SYS_MOV_SEAL_ROW', 'Seal row', 'Pull', 'Barbell or dumbbells, high bench', 'Lats, mid-back, rear delts', 'intermediate',
    'Chest-supported row lying face-down. Zero hip cheat.',
    'Lie on a high bench, pull to the bench, squeeze, lower. If the gym has no high bench, a chest-supported T-bar is the cousin. Slow lowers.'),
  e('SYS_MOV_CHEST_ROW', 'Chest-supported row', 'Pull', 'Incline bench, dumbbells or machine', 'Mid-back, lats, rear delts', 'beginner',
    'Torso on a pad, row. The easiest honest row to coach.',
    'Chest on an incline, pull the bells toward the hips, squeeze the shoulder blades, lower. No torso swing possible. A staple accessory.'),
  e('SYS_MOV_MEADOWS', 'Meadows row', 'Pull', 'Landmine / T-bar', 'Lats, upper back', 'intermediate',
    'One-arm landmine row, staggered stance. Hard contraction, long stretch.',
    'Stand perpendicular to the bar, hinge, pull the sleeve to the hip. Strap optional. Do not rotate the torso into a twist-off. Slow stretch at the bottom.'),
  e('SYS_MOV_TBAR_ROW', 'T-bar row', 'Pull', 'T-bar or landmine with handle', 'Mid-back, lats', 'intermediate',
    'Chest-up or supported T-bar. Classic thickness builder.',
    'Straddle the bar, hinge, pull the handle to the chest. Neutral grips are shoulder-friendly. Do not bounce off the floor unless it is a Pendlay-style dead-stop.'),
  e('SYS_MOV_LANDMINE_ROW', 'Landmine row', 'Pull', 'Barbell in landmine', 'Lats, mid-back', 'beginner',
    'Two-hand or V-handle row on a landmine. Simple and joint-friendly.',
    'Stand over the bar, hinge, pull. A fine first loaded row. Keep the back long. Single-arm is the Meadows if they stand sideways.'),
  e('SYS_MOV_WIDE_PU', 'Wide-grip pull-up', 'Pull', 'Pull-up bar', 'Lats, upper back', 'intermediate',
    'Wider pronated pull-up. More lat width, less elbow flexion.',
    'Hands outside the shoulders, full hang, chin over or chest to bar. Do not go so wide the shoulders shrug into the ears. Band or eccentric scales.'),
  e('SYS_MOV_NEUT_PU', 'Neutral-grip pull-up', 'Pull', 'Parallel bars or rings', 'Lats, biceps, mid-back', 'intermediate',
    'Palms facing. Often the kindest pull-up on the elbows and shoulders.',
    'Full hang, pull until the chin is over, lower. Rings or a multi-grip bar. The usual first unassisted vertical pull after a chin-up.'),
  e('SYS_MOV_C2B', 'Chest-to-bar pull-up', 'Pull', 'Pull-up bar', 'Lats, mid-back, biceps', 'advanced',
    'Pull until the chest meets the bar. Higher standard than a chin-over.',
    'Strict first. The bar hits the sternum / upper chest. Kipping C2B is a metcon skill — write the standard. Scale to jumping C2B or a high pulldown.'),
  e('SYS_MOV_MUSCLE_UP', 'Muscle-up (bar or rings)', 'Pull', 'Bar or rings', 'Lats, triceps, pecs, core', 'advanced',
    'Pull-up that turns into a dip. High skill. Not a class default.',
    'False grip on rings; on a bar, a clean hip pop then sit-through. Teach pulling and dipping separately. Jumping or band muscle-ups if the session needs the pattern. Shoulders must be ready.'),
  e('SYS_MOV_ST_ARM_PULL', 'Straight-arm pulldown', 'Pull', 'Cable, bar or rope', 'Lats', 'beginner',
    'Long-arm lat isolation. Teaches “pull the bar to the hips”.',
    'Slight hinge, arms long, sweep the bar to the thighs, squeeze the lats, return to a stretch. Elbows soft, not a triceps pushdown. A warm-up for pulls and a finisher.'),
  e('SYS_MOV_PULLOVER', 'Dumbbell pullover', 'Pull', 'Dumbbell, bench', 'Lats, pecs, serratus', 'intermediate',
    'Lie on a bench and arc a bell overhead. Long-lever lat and pec stretch.',
    'Upper back on the bench, hips slightly down, lower the bell behind the head with soft elbows, pull back over the chest. Do not turn it into a skull crusher. Light.'),
  e('SYS_MOV_REAR_DELT_FLY', 'Rear-delt fly', 'Pull', 'Dumbbells, cables, or machine', 'Rear delts, mid-traps', 'beginner',
    'Horizontal abduction. The back of the shoulder most pressing ignores.',
    'Hinge or chest-supported, thumbs slightly in or neutral, fly the arms wide, squeeze. Light. A machine reverse pec-deck is the same family. High reps welcome.'),
  e('SYS_MOV_BB_SHRUG', 'Barbell shrug', 'Pull', 'Barbell', 'Upper traps, grip', 'beginner',
    'Elevate the shoulders under a heavy bar. Simple trap work.',
    'Stand tall, shrug straight up, pause, lower. No wild roll. Straps if the grip dies first. Dumbbells or a trap bar are often more comfortable.'),
  e('SYS_MOV_DB_SHRUG', 'Dumbbell shrug', 'Pull', 'Dumbbells', 'Upper traps', 'beginner',
    'Shrugs with bells at the sides. Longer range than a barbell for many people.',
    'Stand tall, shrug, pause, lower. Do not chase huge loads with a half-range. A slight pause at the top is the whole point.'),
  e('SYS_MOV_GORILLA_ROW', 'Gorilla row', 'Pull', 'Two kettlebells', 'Lats, mid-back, core', 'intermediate',
    'Hinged alternating rows from the floor. Dead-stop each side.',
    'Hinge over two bells, row one while the other stays planted, switch. Flat back. A fine class row when there are enough kettlebells.'),
  e('SYS_MOV_HELMS_ROW', 'Helms row', 'Pull', 'Dumbbell, bench or rack', 'Mid-back, rear delts', 'intermediate',
    'Chest-braced single-arm row with a long stretch. Honest and hard.',
    'Brace the free hand and forearm on a bench, row with a slow stretch at the bottom. No torso twist. Moderate load, high quality.'),
  e('SYS_MOV_RING_ROW', 'Ring row', 'Pull', 'Rings', 'Mid-back, lats, core', 'beginner',
    'Inverted row on rings. Unstable and scalable by foot position.',
    'Rings at hip height, body straight, pull the chest to the rings, turn the hands out at the top if they can. Walk the feet to change difficulty.'),
  e('SYS_MOV_BAND_PA', 'Band pull-apart', 'Pull', 'Light band', 'Rear delts, mid-traps', 'beginner',
    'Pull a band apart at chest height. Warm-up and posture work.',
    'Arms long, pull wide without shrugging. 15–25 easy reps. Pair with every press day. Not a max-effort movement.'),

  // ── Carry / odd object ─────────────────────────────────
  e('SYS_MOV_WAITER', 'Waiter carry', 'Carry', 'Kettlebell or dumbbell', 'Shoulder, core, grip', 'intermediate',
    'One load locked out overhead, walk. A lighter, more precise overhead carry.',
    'Palm up, arm by the ear, ribs down, walk. Switch hands. If the elbow unlocks, the set is over. Great for shoulder stability after a press.'),
  e('SYS_MOV_ZERCHER_CARRY', 'Zercher carry', 'Carry', 'Barbell or sandbag', 'Core, upper back, biceps', 'intermediate',
    'Walk with the load in the elbows. Brutal midline and a strongman staple.',
    'Bar or bag in the crook of the elbows, hug it, walk tall. Short distances. Pad the arms. Do not let the pelvis dump forward.'),
  e('SYS_MOV_SANDBAG_CARRY', 'Sandbag carry', 'Carry', 'Sandbag', 'Core, upper back, grip, legs', 'beginner',
    'Hug or shoulder a bag and walk. Odd-object work every gym can do.',
    'Bear-hug, front-loaded, or on one shoulder. Walk without leaning the lumbar spine into it. Re-clean if the bag slides. Distance or time.'),
  e('SYS_MOV_BEAR_HUG', 'Bear-hug carry', 'Carry', 'Sandbag, stone, or D-ball', 'Core, arms, upper back', 'beginner',
    'Squeeze a heavy object to the chest and walk. Simple, ugly, effective.',
    'Arms wrapped, bag high on the chest, short steps. Breathe behind the brace. Drop with control. A class favourite when there are bags.'),
  e('SYS_MOV_YOKE', 'Yoke walk', 'Carry', 'Yoke', 'Whole body, especially trunk and legs', 'advanced',
    'Walk with a yoke on the back. Strongman classic — huge load, short distance.',
    'Set the height so they can stand tall, brace, and walk fast short steps. Dump the implement safely. Not a first carry. Farmer and sandbag first.'),
  e('SYS_MOV_DUCK_WALK', 'Duck walk', 'Carry', 'Kettlebell between the legs or sandbag', 'Quads, glutes, core', 'intermediate',
    'Stay in a squat and waddle. Quads and lungs, little skill.',
    'Hold a bell goblet or between the legs, stay low, walk. Short distances. Knees track. A finisher, not a strength max.'),
  e('SYS_MOV_MIXED_CARRY', 'Mixed / offset carry', 'Carry', 'Two different implements', 'Core, grip, gait', 'intermediate',
    'Farmer in one hand, rack or overhead in the other. Anti-rotation on the move.',
    'Pick two positions, walk, switch. Do not lean. A progression once farmer and rack carries are tidy.'),
  e('SYS_MOV_PLATE_PINCH', 'Plate-pinch carry', 'Carry', 'Weight plates', 'Grip, forearms', 'beginner',
    'Pinch smooth plates and walk. Pure grip.',
    'Two plates pinched smooth-side-out, or one plate by the rim. Short walks. When the pinch fails, the set is over. Chalk helps.'),

  // ── Core extras ────────────────────────────────────────
  e('SYS_MOV_HANG_LR', 'Hanging leg raise', 'Core', 'Pull-up bar', 'Hip flexors, abs, grip', 'intermediate',
    'Hang and lift straight legs. The step after knee raises.',
    'Dead hang, ribs down, raise the legs toward horizontal or higher without swinging. Lower slowly. Bent knees if they pike. Toes-to-bar is next.'),
  e('SYS_MOV_TTB', 'Toes-to-bar', 'Core', 'Pull-up bar', 'Abs, hip flexors, lats, grip', 'advanced',
    'Hang and touch the toes to the bar. Gymnastics kipping or strict.',
    'Write the standard: strict or kipping. Hollow and arch for kipping. Strict is a controlled pike to the bar. Scale to knee raises or lying leg raises. Shoulders packed.'),
  e('SYS_MOV_LSIT', 'L-sit', 'Core', 'Parallettes, rings, or floor', 'Hip flexors, abs, triceps', 'advanced',
    'Support hold with the legs straight out. Isometric gold.',
    'Locked arms, legs long and off the floor, chest up. Tuck sit and one-leg L are the scales. Short holds, 10–20 seconds. Do not shrug.'),
  e('SYS_MOV_VUP', 'V-up', 'Core', 'Floor', 'Abs, hip flexors', 'intermediate',
    'Simultaneous arm and leg pike into a V. Fast midline work.',
    'Start hollow-ish, reach hands to feet, lower with control. Bent-knee tuck-ups if they cannot pike. Do not yank the neck. Slow is harder and better.'),
  e('SYS_MOV_SITUP', 'Sit-up', 'Core', 'Floor, abmat optional', 'Abs, hip flexors', 'beginner',
    'The classic sit-up. Simple, easy to rush, easy to yank the neck.',
    'Feet anchored or not — write it. Sit up, touch, lower. Abmat under the lumbar if they like the range. Butterfly sit-ups (soles together) are a common class standard.'),
  e('SYS_MOV_CRUNCH', 'Crunch', 'Core', 'Floor', 'Abs', 'beginner',
    'Short-range spinal flexion. Less hip flexor than a full sit-up.',
    'Ribs toward the pelvis, shoulders off the floor, pause, lower. Hands by the temples, not yanking the head. High reps or a slow tempo. A warm-up, not a sport.'),
  e('SYS_MOV_BICYCLE', 'Bicycle crunch', 'Core', 'Floor', 'Abs, obliques', 'beginner',
    'Alternating elbow-to-knee. Easy to flop; still useful when done slowly.',
    'Shoulders off the floor, opposite elbow toward opposite knee, long slow switches. Do not pull the neck. Quality over speed.'),
  e('SYS_MOV_RUS_TWIST', 'Russian twist', 'Core', 'Floor, optional plate', 'Obliques', 'beginner',
    'Seated rotation. Popular, often sloppy — coach the posture first.',
    'Lean back with a long spine, rotate the shoulders, not just the arms. Feet can stay down to scale. A plate or ball is optional. Stop if the lumbar rounds hard.'),
  e('SYS_MOV_WOODCHOP', 'Cable woodchop', 'Core', 'Cable or band', 'Obliques, core', 'beginner',
    'Diagonal chop high-to-low or low-to-high. Rotation you can load.',
    'Feet planted, rotate through the ribs, arms long. Do not yank with the arms only. High-to-low and low-to-high are both useful. Controlled tempo.'),
  e('SYS_MOV_LM_ROT', 'Landmine rotation', 'Core', 'Barbell in landmine', 'Obliques, core, shoulders', 'intermediate',
    'Arc a landmine from hip to hip. Loaded rotation with a simple tool.',
    'Stand facing the landmine, sweep the sleeve in a rainbow while the hips stay fairly quiet (or allow a small pivot). Moderate load. Do not yank the low back.'),
  e('SYS_MOV_COPENHAGEN', 'Copenhagen plank', 'Core', 'Bench', 'Adductors, obliques', 'intermediate',
    'Side plank with the top leg on a bench. Adductor strength that prevents a lot of groin issues.',
    'Top foot or shin on a bench, bottom leg tucked or long, hips high. Short holds. Knee-on-bench is the scale. Brutal and worth it for field athletes.'),
  e('SYS_MOV_STIR_POT', 'Stir the pot', 'Core', 'Swiss ball', 'Anterior core, shoulders', 'intermediate',
    'Plank on a ball with small circles. Anti-extension plus a bit of chaos.',
    'Forearms on the ball, body long, small circles both ways. Do not let the hips sag. Short sets. A plank on the floor if the ball is a circus.'),
  e('SYS_MOV_GHD_SIT', 'GHD sit-up', 'Core', 'GHD', 'Hip flexors, abs', 'advanced',
    'Full-range sit-up on a GHD. Famous, spicy on the hip flexors and lumbar.',
    'Set the hips just off the pad, lower with control, sit up. Arms can swing for kipping-style. Not a first sit-up. Build with decline sit-ups and hanging raises. Soreness is real — introduce slowly.'),
  e('SYS_MOV_DRAGON', 'Dragon flag', 'Core', 'Bench', 'Abs, hip flexors, lats', 'advanced',
    'Bruce Lee’s hold. Full-body anti-extension from the shoulders.',
    'Hold the bench behind the head, lift the body into a straight line, lower slowly. Tucked negatives first. Not a class-wide movement. Hollow holds and roll-outs first.'),
  e('SYS_MOV_WIPER', 'Windshield wiper', 'Core', 'Bar or floor', 'Obliques, abs, grip', 'advanced',
    'Hanging or lying, sweep the legs side to side. Hard rotational core.',
    'From a hanging L or a lying hollow, move the legs as a unit. Slow. Bent knees to scale. Do not yank the lumbar. Floor wipers are the honest start.'),
  e('SYS_MOV_MTN_CLIMB', 'Mountain climber', 'Core', 'Floor', 'Core, hip flexors, shoulders', 'beginner',
    'Plank with alternating knees. Conditioning more than a max-strength core lift.',
    'Hold a strong plank, drive the knees. Slow for core, fast for a finisher. Hips stay level. Hands on a box to scale the wrists.'),
  e('SYS_MOV_FLUTTER', 'Flutter kick', 'Core', 'Floor', 'Hip flexors, abs', 'beginner',
    'Hollow-ish position, small kicks. Simple midline burn.',
    'Low back down, shoulders off if they can, small alternating kicks. Hands under the hips to scale. Stop when the back peels up.'),
  e('SYS_MOV_REV_CRUNCH', 'Reverse crunch', 'Core', 'Floor', 'Abs', 'beginner',
    'Curl the pelvis toward the ribs. Less neck yank than a crunch.',
    'Knees bent, lift the hips and curl, lower without slamming. Slow. A cable or decline version is optional. Quality over swinging.'),
  e('SYS_MOV_CABLE_CRUNCH', 'Cable crunch', 'Core', 'Cable, rope', 'Abs', 'beginner',
    'Kneeling flexion against a cable. Loadable sit-up pattern.',
    'Kneel, rope at the shoulders, crunch the ribs to the pelvis, return. This is not a hip hinge. Moderate load, full squeeze. Keep the neck long.'),
  e('SYS_MOV_HOLLOW_ROCK', 'Hollow rock', 'Core', 'Floor', 'Anterior core', 'intermediate',
    'Rock in a hollow hold. Gymnastics midline that exposes leaks.',
    'Set a tight hollow, then small rocks. If they break, they go back to a hold. Arms by the ears if possible. A class standard in many gyms.'),
  e('SYS_MOV_RKC_PLANK', 'RKC / hard-style plank', 'Core', 'Floor', 'Full anterior chain, glutes', 'intermediate',
    'Short, maximal-tension plank. 10 honest seconds beat a two-minute sag.',
    'Elbows in, fists, squeeze everything — glutes, quads, lats — and breathe behind the brace. Short sets. Coach the tension, not the clock.'),

  // ── Olympic / barbell cycling ──────────────────────────
  e('SYS_MOV_SQUAT_CLEAN', 'Squat clean', 'Olympic', 'Barbell', 'Full body', 'advanced',
    'Clean received in a full front squat. The competition catch.',
    'Pull, pull under, catch in a deep front squat, stand. Only if they can front squat the load. Teach power clean and front squat first. Quality singles.'),
  e('SYS_MOV_MUSCLE_CLEAN', 'Muscle clean', 'Olympic', 'Barbell or PVC', 'Traps, arms, upper back', 'intermediate',
    'Clean with no dip under the bar. Teaches the turnover.',
    'Pull and punch the elbows through without sitting. Light. A teaching drill and a warm-up, not a heavy lift.'),
  e('SYS_MOV_CLEAN_PULL', 'Clean pull', 'Olympic', 'Barbell', 'Hips, back, traps', 'intermediate',
    'Deadlift that finishes with a violent shrug and long arms. Strength for the clean.',
    'Clean grip, same set as a clean, extend hard, no catch. Heavier than they can clean. Do not turn it into a sloppy high pull with bent arms unless you programmed a high pull.'),
  e('SYS_MOV_HANG_PC', 'Hang power clean', 'Olympic', 'Barbell', 'Hips, traps, legs', 'intermediate',
    'Power clean from the hang. The most useful Olympic variation in a general gym.',
    'Hinge to above the knee, jump and rack, catch high. Easy to cycle in classes. Teach the rack and the jump before the floor.'),
  e('SYS_MOV_PWR_SNATCH', 'Power snatch', 'Olympic', 'Barbell', 'Full body', 'advanced',
    'Snatch received above parallel. Faster and more athletic than a full snatch for most gyms.',
    'Wide grip, pull and catch overhead with the hips high. PVC and hang first. Full squat snatch only if mobility and coaching allow.'),
  e('SYS_MOV_HANG_SNATCH', 'Hang snatch', 'Olympic', 'Barbell', 'Hips, shoulders, back', 'advanced',
    'Snatch from the hang. Easier to teach than the floor.',
    'Hinge to the hang, extend, catch overhead. Power or full. Light and crisp. A teaching and power tool.'),
  e('SYS_MOV_MUSCLE_SNATCH', 'Muscle snatch', 'Olympic', 'Barbell or PVC', 'Traps, shoulders, upper back', 'intermediate',
    'Snatch with no dip under. Teaches the turnover to overhead.',
    'Pull and punch the bar overhead without sitting. Very light. Warm-up and skill, not a heavy day.'),
  e('SYS_MOV_SNATCH_PULL', 'Snatch pull', 'Olympic', 'Barbell', 'Hips, back, traps', 'intermediate',
    'Snatch-grip pull without the catch. Strength for the snatch.',
    'Wide grip, long arms, violent extension. Heavier than they can snatch. Keep the bar close. No early arm bend unless it is a high pull.'),
  e('SYS_MOV_SNATCH_BAL', 'Snatch balance', 'Olympic', 'Barbell', 'Shoulders, legs, trunk', 'advanced',
    'Dip and drop under a back-racked bar into an overhead squat. Teaches receiving.',
    'Bar on the back, dip, drive, punch under into a squat. Light. Only if they can overhead squat. A skill drill, not a metcon.'),
  e('SYS_MOV_SPLIT_JERK', 'Split jerk', 'Olympic', 'Barbell', 'Legs, shoulders, trunk', 'advanced',
    'Jerk received in a split stance. The usual competition jerk.',
    'Dip, drive, split — one foot forward, one back — arms locked, then recover. Footwork first with a PVC. Push jerk is the simpler cousin.'),
  e('SYS_MOV_THRUSTER', 'Thruster', 'Olympic', 'Barbell, dumbbells, or kettlebells', 'Quads, shoulders, core', 'intermediate',
    'Front squat straight into an overhead press. The class engine everyone loves to hate.',
    'Front rack, full squat, drive into a press in one piece. No pause to collect themselves unless the standard allows it. Write the depth and the lockout. DB and KB thrusters are honest scales.'),
  e('SYS_MOV_CLUSTER', 'Cluster (clean + thruster)', 'Olympic', 'Barbell', 'Full body', 'advanced',
    'Squat clean into a thruster. One of the hardest barbell cycles.',
    'Clean to a full squat, then stand and press in one motion (or stand then thruster — write it). Not a beginner complex. Power-clean + push-press is the scale.'),
  e('SYS_MOV_C_AND_J', 'Clean and jerk', 'Olympic', 'Barbell', 'Full body', 'advanced',
    'The two-part Olympic lift. Clean, then jerk.',
    'Treat it as two skills glued together. Rest in the rack if they need it. Push jerk is acceptable in a fitness class if split jerk is not coached. Quality over load.'),
  e('SYS_MOV_WALL_BALL', 'Wall ball', 'Conditioning', 'Medicine ball, wall', 'Quads, shoulders, lungs', 'beginner',
    'Squat and throw a ball to a target. The CrossFit-style conditioner.',
    'Goblet the ball, full squat, explode and throw to the marked height, catch, repeat. Write the target height and the squat depth. A lighter ball or a target they can reach is the scale.'),
  e('SYS_MOV_KB_SNATCH', 'Kettlebell snatch', 'Olympic', 'Kettlebell', 'Hips, lats, shoulders, core', 'advanced',
    'Swing that finishes locked out overhead. Ballistic and technical.',
    'Hike, hip snap, punch through at the top so the bell does not flop on the wrist. Soft landing on the forearm. Teach the swing and the high pull first. One arm.'),
  e('SYS_MOV_KB_CLEAN', 'Kettlebell clean', 'Olympic', 'Kettlebell', 'Hips, upper back, core', 'intermediate',
    'Swing to the rack. The gateway to KB front squats and presses.',
    'Hike, snap, the bell rolls around the wrist into a quiet rack — not a crash. Upper-arm against the body. Teach this before a KB snatch or a heavy rack carry.'),
  e('SYS_MOV_TGU', 'Turkish get-up', 'Core', 'Kettlebell or dumbbell', 'Shoulder, core, hips — whole body', 'intermediate',
    'From lying to standing with a load locked out. Slow strength and shoulder stability.',
    'Teach naked (no bell) first. Punch the bell up, roll to the elbow, to the hand, sweep the leg, half-kneeling, stand — reverse it. Eyes on the bell. Light. A skill, not a metcon.'),

  // ── Plyometric extras ──────────────────────────────────
  e('SYS_MOV_DEPTH_JUMP', 'Depth jump', 'Plyometric', 'Box', 'Quads, glutes, calves, tendons', 'advanced',
    'Step off a box and jump immediately on landing. True stretch-shortening work.',
    'Step off, land quiet, bounce into a vertical or broad jump. Low box first. This is not a drop-and-stick (that is a depth drop). Low volume. Not for deconditioned knees.'),
  e('SYS_MOV_DROP_JUMP', 'Depth drop / stick landing', 'Plyometric', 'Box', 'Quads, glutes, calves', 'intermediate',
    'Step off a box and stick the landing. Teaches absorption before rebound.',
    'Step off, land in an athletic stance, freeze. Quiet feet. The first plyo after they can squat and hinge. Then add a jump if you want a depth jump.'),
  e('SYS_MOV_TUCK_JUMP', 'Tuck jump', 'Plyometric', 'Bodyweight', 'Quads, hip flexors, calves', 'intermediate',
    'Jump and tuck the knees. Simple vertical power.',
    'Jump, knees up, land soft, reset or cycle. Short sets. Not a warm-up for new members. Quiet landings or the set is over.'),
  e('SYS_MOV_SPLIT_JUMP', 'Split jump', 'Plyometric', 'Bodyweight', 'Quads, glutes', 'intermediate',
    'Jump in a split stance and land in the same stance (or switch).',
    'Same as a jumping lunge if they switch. Stay in stance for less chaos. Soft knees. A power primer for lunges and sprints.'),
  e('SYS_MOV_POGO', 'Pogo jump', 'Plyometric', 'Bodyweight', 'Calves, Achilles', 'beginner',
    'Stiff-ankle bounces. Tendon stiffness and a warm-up for jumping.',
    'Almost straight knees, bounce on the balls of the feet, quiet and rhythmic. 10–20 contacts. A primer, not a burnout. Barefoot or trainers, not squishy max-cushion if you can help it.'),
  e('SYS_MOV_BOUND', 'Bound / power skip', 'Plyometric', 'Open floor', 'Glutes, calves, hips', 'intermediate',
    'Exaggerated skips or bounds for distance. Horizontal power.',
    'Drive the knee and opposite arm, cover ground. Short runway. Not a crowded-studio move. Pogos and broad jumps first.'),
  e('SYS_MOV_SKATER', 'Skater jump', 'Plyometric', 'Floor', 'Glutes, abductors, calves', 'beginner',
    'Side-to-side bounds. Frontal-plane power.',
    'Push off one leg, land on the other, quiet, then go. Stick or cycle. A warm-up for cuts and for lateral lunges. Soft knees.'),
  e('SYS_MOV_LAT_BOUND', 'Lateral bound', 'Plyometric', 'Floor', 'Glutes, adductors, calves', 'intermediate',
    'Bigger sideways jump than a skater. Stick the landing.',
    'Load one hip, jump far sideways, stick. Reset. Low volume. Skaters first. Do not let the landing knee cave.'),
  e('SYS_MOV_HURDLE', 'Hurdle hop', 'Plyometric', 'Mini hurdles', 'Calves, quads, hips', 'intermediate',
    'Consecutive hops over low hurdles. Rhythm and elasticity.',
    'Low hurdles, quiet contacts, stay tall. Stop when they clip or get loud. A track-and-field tool that works in a gym if you have the space.'),
  e('SYS_MOV_SEAT_BOX', 'Seated box jump', 'Plyometric', 'Low box to sit, jump box', 'Quads, glutes', 'intermediate',
    'Jump from a seated start. No stretch-shortening — pure concentric power.',
    'Sit tall on a low box, explode onto a jump box, stand, step down. Great when you want power without a rebound. Low volume.'),
  e('SYS_MOV_MB_CHEST', 'Medicine-ball chest pass', 'Plyometric', 'Medicine ball, wall or partner', 'Pecs, triceps, core', 'beginner',
    'Explosive chest throw. Upper-body power without a barbell.',
    'Athletic stance, throw hard to a wall or partner, catch or reset. A slam ball will not bounce — use a bounce ball or a wall-ball. Short sets of crisp throws.'),
  e('SYS_MOV_MB_OH', 'Medicine-ball overhead throw', 'Plyometric', 'Medicine ball', 'Lats, core, shoulders, hips', 'beginner',
    'Throw the ball backward or forward from overhead. Hip and upper-body power.',
    'Hinge or squat slightly, throw. Backward scoop throws need space. Forward overhead is easier to control in a gym. Light ball, hard intent.'),
  e('SYS_MOV_MB_ROT', 'Medicine-ball rotational throw', 'Plyometric', 'Medicine ball, wall', 'Obliques, hips, shoulders', 'intermediate',
    'Side throw into a wall. Rotational power for field sports.',
    'Stand side-on, load the hip, throw into the wall, catch or reset. Both sides. A slam is not a rotation — this is a throw. Clear the area.'),
  e('SYS_MOV_BBJ', 'Burpee box jump', 'Plyometric', 'Box', 'Full body', 'intermediate',
    'Burpee into a box jump. Nasty conditioner. Write the standard.',
    'Chest-to-deck or not, then jump on the box and stand. Step down. A burpee + step-up is the scale. Not a first session for new members.'),

  // ── Conditioning extras ────────────────────────────────
  e('SYS_MOV_DU', 'Double-under', 'Conditioning', 'Speed rope', 'Calves, shoulders, lungs', 'intermediate',
    'Two rope turns per jump. Skill plus conditioning.',
    'Singles must be relaxed first. Wrists turn, small jumps. Short practice sets beat failure death-marches. Scale to singles or a bike. Rope length matters.'),
  e('SYS_MOV_SLED_PUSH', 'Sled push', 'Conditioning', 'Sled or prowler', 'Quads, glutes, calves, lungs', 'beginner',
    'Push a sled. Joint-friendly, scalable, honest work.',
    'Low or high handles, forward lean, drive the legs. Short heavy trips or longer lighter ones. No eccentric — great when people are sore. Clear the bay.'),
  e('SYS_MOV_SLED_PULL', 'Sled pull', 'Conditioning', 'Sled, straps or rope', 'Hamstrings, back, grip, lungs', 'beginner',
    'Drag a sled walking backward or facing it with a rope.',
    'Backward walk for the quads and knees; rope-over-shoulder for the posterior chain. Short distances. A complement to the push, not a replacement.'),
  e('SYS_MOV_PROWLER', 'Prowler push', 'Conditioning', 'Prowler', 'Quads, glutes, lungs', 'beginner',
    'The classic high-handle or low-handle prowler. Same family as a sled push.',
    'Low handles = more horizontal and usually harder. Short heavy, long light. Do not let the hips pike up and walk with straight legs unless that is the point.'),
  e('SYS_MOV_SHUTTLE', 'Shuttle run', 'Conditioning', 'Cones, floor', 'Legs, lungs, change of direction', 'beginner',
    'Run out and back. Simple, space-hungry, effective.',
    'Mark 5–20 m, touch the line, turn. Write the touches. A bike or rower if the floor is crowded or the members cannot change direction safely.'),
  e('SYS_MOV_VERSA', 'VersaClimber', 'Conditioning', 'VersaClimber', 'Full body, lungs', 'beginner',
    'Vertical climb machine. Huge engine, low impact.',
    'Long strokes, opposite arm and leg. Metres or time. New users go too short and too frantic — coach the stroke. A rower if the gym has no climber.'),
  e('SYS_MOV_STAIR', 'Stair climber / stepmill', 'Conditioning', 'Stepmill', 'Quads, glutes, calves, lungs', 'beginner',
    'Endless stairs. Simple, sweaty, knee-aware if they stand tall.',
    'Whole foot, stand up, do not lean hard on the rails. Time or floors. A sled or bike if the machine line is long.'),
  e('SYS_MOV_ELLIP', 'Elliptical', 'Conditioning', 'Elliptical', 'Legs, lungs', 'beginner',
    'Low-impact gait machine. Fine for deconditioned or irritable-joint members.',
    'Stand tall, use the arms if it has them. Time or distance. Not a skill. A valid substitution for running.'),
  e('SYS_MOV_BIKE_ERG', 'Bike erg', 'Conditioning', 'Concept2 bike erg or similar', 'Legs, lungs', 'beginner',
    'Seated fan or air bike without the arms. Pure legs and lungs.',
    'Smooth circles, damper to taste. Calories, metres, or watts. Easier on the upper body than an assault bike. Teach the damper before a test.'),
  e('SYS_MOV_TM_INCLINE', 'Incline treadmill walk', 'Conditioning', 'Treadmill', 'Glutes, calves, lungs', 'beginner',
    'Steep walk. Joint-friendlier than a run, still honest work.',
    '6–15% grade, brisk walk, no hands if they can. Time. A hill they can talk on is aerobic; a hill they cannot is a finisher. Safety clip on.'),
  e('SYS_MOV_SWIM', 'Swim', 'Conditioning', 'Pool', 'Full body, lungs', 'beginner',
    'The original full-body conditioner. Only if the gym has water or a partner pool.',
    'Set stroke and distance. Easy aerobic or intervals. Not every member swims — give a rower or ski as the stand-in. Never programme this without a real option.'),
  e('SYS_MOV_FAN_WALK', 'Air-bike walk / easy spin', 'Conditioning', 'Air bike', 'Legs, lungs', 'beginner',
    'Easy air-bike as a warm-up or recovery spin. Intent matters.',
    'Low watts, nasal breathing if you like, 3–8 minutes. Do not let it become a silent suffer-fest unless that is the session. Teach zones if the gym uses them.'),

  // ── Mobility extras ────────────────────────────────────
  e('SYS_MOV_PIGEON', 'Pigeon stretch', 'Mobility', 'Floor', 'Glutes, external rotators', 'beginner',
    'Front shin across, back leg long. Classic glute and hip stretch.',
    'Keep the hips square, fold forward if they like. A box or bolster under the hip if they roll. 45–90 seconds. 90/90 is the more controllable cousin.'),
  e('SYS_MOV_HK_FLEX', 'Half-kneeling hip-flexor stretch', 'Mobility', 'Floor', 'Hip flexors', 'beginner',
    'The simple couch-stretch cousin. Every squat and run warm-up.',
    'Back knee down, squeeze that glute, stay tall, optional side bend. 45 seconds a side. Do not dump the lumbar spine forward.'),
  e('SYS_MOV_CHILD', 'Child’s pose', 'Mobility', 'Floor', 'Lats, low back, hips', 'beginner',
    'Sit the hips back, arms long. A quiet reset between hard sets.',
    'Big toes together or knees wide. Breathe into the back. Walk the hands to one side for a lat bias. 30–60 seconds. Not a nap — a reset.'),
  e('SYS_MOV_DDOG', 'Downward dog', 'Mobility', 'Floor', 'Hamstrings, calves, shoulders', 'beginner',
    'Inverted V. Posterior chain and shoulder stretch in one shape.',
    'Hands and feet planted, hips high, heels working down. Pedal the feet. Soft knees if the hamstrings are loud. A warm-up, not a max stretch contest.'),
  e('SYS_MOV_THREAD', 'Thread the needle', 'Mobility', 'Floor', 'T-spine, rear shoulder', 'beginner',
    'Quadruped reach-through. Gentle thoracic rotation.',
    'From all fours, slide one arm under the other and rest on the shoulder, breathe, then stack and open if you like. Slow. Pair with open-books.'),
  e('SYS_MOV_WALL_SLIDE', 'Wall slide / scap slide', 'Mobility', 'Wall', 'Mid-traps, rotator cuff, T-spine', 'beginner',
    'Back on a wall, arms slide up. Shoulder and upper-back prep.',
    'Ribs down, back of the hands or elbows on the wall if they can, slide up without the ribs flaring. A short range is still useful. Before every press.'),
  e('SYS_MOV_PEC_STRETCH', 'Doorway pec stretch', 'Mobility', 'Doorway or rack', 'Pectorals, anterior delts', 'beginner',
    'Open the chest on a doorframe. Counters desk life and too much pressing.',
    'Forearm on the frame, step through, gentle. One arm at a time. 30–45 seconds. Do not crank into the front shoulder.'),
  e('SYS_MOV_LAT_STRETCH', 'Lat stretch (rack or band)', 'Mobility', 'Rack or band', 'Lats, T-spine', 'beginner',
    'Long-arm hang or banded lat stretch. Helps overhead and the squat bar path.',
    'Grab a rack high, sit the hips back, breathe. Or a band overhead and hinge. 30–45 seconds a side. Pair with wall slides.'),
  e('SYS_MOV_CALF_STRETCH', 'Calf stretch', 'Mobility', 'Wall or step', 'Gastrocnemius, soleus', 'beginner',
    'Straight-knee and bent-knee calf stretches. Ankle food for squats and running.',
    'Hands on a wall, back leg long (gastroc), then slightly bent (soleus). 45 seconds each. A step hang is the same idea. Daily if they squat deep.'),
  e('SYS_MOV_HS_STRETCH', 'Hamstring stretch (active or strap)', 'Mobility', 'Strap or floor', 'Hamstrings', 'beginner',
    'Long-leg stretch. Active (lift the leg) beats a dead hang for most athletes.',
    'Lie on the back, strap on the foot, keep the other leg long, gently pull or actively lift. 30–45 seconds. Do not yank into a rounded spine from standing unless you meant a Jefferson curl.'),
  e('SYS_MOV_FROG', 'Frog stretch', 'Mobility', 'Floor', 'Adductors', 'beginner',
    'Knees wide, sit the hips back. Adductor length for squats and Cossacks.',
    'On all fours, knees out, rock back gently. Pads under the knees. Stop if the hips pinch in the front. 45–60 seconds.'),
  e('SYS_MOV_ADD_ROCK', 'Adductor rock-back', 'Mobility', 'Floor', 'Adductors, hips', 'beginner',
    'Half-kneeling with one leg out to the side, rock toward it. Controlled adductor work.',
    'Inside knee down, other leg long to the side, rock over the straight leg and back. Smooth. A better warm-up than a static split for many people.'),
  e('SYS_MOV_BRETZEL', 'Bretzel stretch', 'Mobility', 'Floor', 'T-spine, hip flexor, glute', 'beginner',
    'Side-lying twist that hits the hip flexor, glute, and mid-back together.',
    'Bottom knee pulled up, top hand holding the rear foot, rotate the chest open. Breathe. 45–60 seconds a side. A warm-up favourite.'),
  e('SYS_MOV_SQUAT_HOLD', 'Deep squat hold', 'Mobility', 'Floor, optional plate for counterweight', 'Ankles, hips, back', 'beginner',
    'Sit in a deep squat and stay. The pattern they need to own.',
    'Heels down if possible, elbows inside the knees, breathe. Hold a plate or a rack if they fall backward. 30–90 seconds. Daily if they sit a lot.'),
  e('SYS_MOV_DEAD_HANG', 'Dead hang', 'Mobility', 'Pull-up bar', 'Lats, grip, shoulders', 'beginner',
    'Hang from a bar and breathe. Shoulder decompression and grip.',
    'Active (shoulders packed) or passive — write which. 20–45 seconds. Not a shrug. Step down; do not drop from a high bar onto stiff knees.'),
  e('SYS_MOV_WRIST_MOB', 'Wrist mobility flow', 'Mobility', 'Floor', 'Wrists, forearms', 'beginner',
    'Rocks and rotations on the hands. Before push-ups, handstands, and cleans.',
    'On all fours, rock over the palms, then fingers back if they can, then fists. 30–60 seconds. A small thing that saves a lot of wrists.'),
  e('SYS_MOV_JEFF_CURL', 'Jefferson curl', 'Mobility', 'Light bar or DB', 'Erectors, hamstrings', 'advanced',
    'Slow, loaded spinal flexion. Advanced. Not a class-wide default.',
    'Very light, stand on a box, tuck the chin and roll down vertebra by vertebra, then roll up. This is not a deadlift. Skip it if they have an irritable back or no coaching.'),

  // ── Isolation extras ───────────────────────────────────
  e('SYS_MOV_HAMMER_CURL', 'Hammer curl', 'Isolation', 'Dumbbells', 'Brachialis, biceps, forearms', 'beginner',
    'Neutral-grip curl. Thickens the arm and is kind to the wrist.',
    'Palms in, upper arms still, curl, lower. No swing. Alternating or together. A default curl when the wrists dislike a barbell.'),
  e('SYS_MOV_PREACHER', 'Preacher curl', 'Isolation', 'Preacher bench, EZ-bar or DB', 'Biceps', 'beginner',
    'Curl with the upper arms on a pad. Hard to cheat.',
    'Armpit at the top of the pad, full stretch, curl without the shoulders shrugging. EZ-bar is friendlier than a straight bar. Control the lower — that is the work.'),
  e('SYS_MOV_INCLINE_CURL', 'Incline dumbbell curl', 'Isolation', 'Dumbbells, incline bench', 'Biceps (long head)', 'beginner',
    'Curl on an incline. Long stretch at the bottom.',
    'Sit back on 45–60°, arms hanging, curl without swinging. Full stretch every rep. Light. A quality accessory, not an ego lift.'),
  e('SYS_MOV_CONC_CURL', 'Concentration curl', 'Isolation', 'Dumbbell', 'Biceps', 'beginner',
    'Seated, elbow on the inner thigh. The isolation curl everyone knows.',
    'Sit, brace the elbow, curl, squeeze, lower. Slow. Not a heavy movement. Finishers of 10–15 work well.'),
  e('SYS_MOV_CABLE_CURL', 'Cable curl', 'Isolation', 'Cable, bar or rope', 'Biceps', 'beginner',
    'Curl against a cable. Constant tension, including at the bottom.',
    'Standing, elbows pinned, curl, lower to a stretch. Rope hammers or a straight bar. Do not lean back to finish the stack.'),
  e('SYS_MOV_EZ_CURL', 'EZ-bar curl', 'Isolation', 'EZ-bar', 'Biceps', 'beginner',
    'The default barbell curl for most gyms. Kinder wrists than a straight bar.',
    'Stand tall, curl without swinging, lower. A slight lean is a cheat. Strict first. Reverse-grip on the same bar is a different movement.'),
  e('SYS_MOV_REV_CURL', 'Reverse curl', 'Isolation', 'EZ-bar or dumbbells', 'Brachioradialis, biceps', 'beginner',
    'Pronated curl. Forearms and a little biceps.',
    'Palms down, curl, lower. Light. A useful accessory for pull-ups and for elbows that need some tendon work — keep the pain-free range.'),
  e('SYS_MOV_OH_TRI', 'Overhead triceps extension', 'Isolation', 'Dumbbell, EZ-bar, or cable', 'Triceps (long head)', 'beginner',
    'Elbows up, extend overhead. Long-head bias.',
    'Seated or standing, lower behind the head, extend. Elbows stay relatively still. A cable keeps tension. Do not flare into a pullover.'),
  e('SYS_MOV_KICKBACK', 'Triceps kickback', 'Isolation', 'Dumbbells or cable', 'Triceps', 'beginner',
    'Hinged, upper arm pinned, extend the elbow. Light and strict.',
    'Hinge, upper arm by the side, extend to lockout, squeeze, return. If they have to swing, the bell is too heavy. Cables are nicer at the end range.'),
  e('SYS_MOV_FRONT_RAISE', 'Front raise', 'Isolation', 'Dumbbells, plate, or cable', 'Anterior delts', 'beginner',
    'Raise the arms in front. Easy to heave — keep it light.',
    'Slight elbow bend, raise to shoulder height, lower. Alternate or together. A plate can work. Not a first shoulder day if they already press a lot.'),
  e('SYS_MOV_UPRIGHT_ROW', 'Upright row', 'Isolation', 'EZ-bar, DB, or cable', 'Delts, traps', 'intermediate',
    'Pull a bar up the body. Effective, and spicy for some shoulders.',
    'Hands inside the shoulders, pull to the lower chest / upper abs, elbows high. Stop if the front shoulder nips — switch to laterals and face pulls. A rope cable is often kinder.'),
  e('SYS_MOV_CABLE_LAT', 'Cable lateral raise', 'Isolation', 'Low cable', 'Lateral delts', 'beginner',
    'Side raise against a cable. Tension at the bottom that dumbbells lack.',
    'Stand side-on, pull the handle out to shoulder height, lower under control. Behind-the-back setup is a nice variant. Light. High reps.'),
  e('SYS_MOV_MACH_LAT', 'Machine lateral raise', 'Isolation', 'Lateral-raise machine', 'Lateral delts', 'beginner',
    'Machine side raise. Simple loading for new members.',
    'Pads on the elbows or handles in the hands — follow the machine. Raise to shoulder height, lower. Do not shrug. A valid isolation when DBs get sloppy.'),
  e('SYS_MOV_HIP_ABD', 'Hip abduction (machine or band)', 'Isolation', 'Abductor machine or band', 'Glute medius', 'beginner',
    'Push the knees or legs out. Lateral hip that lunges and running need.',
    'Machine: sit, push out, control in. Band: around the knees, walk or clam. Slow. A warm-up and a rehab staple. Not a max-effort circus.'),
  e('SYS_MOV_HIP_ADD', 'Hip adduction machine', 'Isolation', 'Adductor machine', 'Adductors', 'beginner',
    'Squeeze the legs together. The inside thigh most people skip.',
    'Sit, squeeze, control the open. Moderate range. Pair with abduction and Cossacks. Stop if the groin nips — this is not a stretch contest.'),
  e('SYS_MOV_SEAT_CALF', 'Seated calf raise', 'Isolation', 'Seated calf machine or plate on knees', 'Soleus', 'beginner',
    'Bent-knee calf raise. Soleus, the endurance calf.',
    'Pad on the knees, full stretch, full squeeze, pause. High reps. Standing calves do not replace this if you care about the soleus.'),
  e('SYS_MOV_DONKEY_CALF', 'Donkey calf raise', 'Isolation', 'Donkey machine or hip hinge on a step', 'Gastrocnemius', 'beginner',
    'Hinged calf raise. A long stretch and an old-school favourite.',
    'Hinge, balls of the feet on a step, full range. A partner or a machine for load. Slow. Standing single-leg is the usual stand-in.'),
  e('SYS_MOV_WRIST_CURL', 'Wrist curl', 'Isolation', 'Barbell or dumbbells', 'Forearm flexors', 'beginner',
    'Forearm flexion. Grip insurance.',
    'Forearms on a bench, palms up, curl the wrists, lower to a stretch. Light, high reps. Reverse wrist curls (palms down) are the pair.'),
  e('SYS_MOV_REV_WRIST', 'Reverse wrist curl', 'Isolation', 'Barbell or dumbbells', 'Forearm extensors', 'beginner',
    'Palms-down wrist extension. The other half of the forearm.',
    'Forearms on a bench, palms down, extend, lower. Very light. Useful for elbows that do a lot of pulling and curling.'),

  // ── Crawls, carries of the body, KB / hybrid ───────────
  e('SYS_MOV_BEAR_CRAWL', 'Bear crawl', 'Conditioning', 'Floor', 'Shoulders, core, legs', 'beginner',
    'Crawl on hands and feet, knees hovering. Full-body conditioner.',
    'Hands under shoulders, knees under hips, hover the knees, opposite hand and foot. Slow for quality, faster for a finisher. Hips stay level. A class staple.'),
  e('SYS_MOV_CRAB_WALK', 'Crab walk', 'Conditioning', 'Floor', 'Shoulders, glutes, hamstrings, core', 'beginner',
    'Supine crawl. Unusual, useful, and a bit humbling.',
    'Hips up, fingers forward or back (forward is kinder on the shoulders), walk. Short distances. A warm-up or a finisher, not a strength max.'),
  e('SYS_MOV_INCHWORM', 'Inchworm', 'Mobility', 'Floor', 'Hamstrings, core, shoulders', 'beginner',
    'Walk the hands out to a plank and back. Warm-up flow.',
    'Hinge, hands to the floor, walk out to a plank, optional push-up, walk back. Soft knees if the hamstrings are loud. Two to four as a start.'),
  e('SYS_MOV_RENEGADE', 'Renegade row', 'Pull', 'Dumbbells or kettlebells', 'Lats, core, shoulders', 'intermediate',
    'Plank row. Anti-rotation plus a pull. Easy to turn into a circus.',
    'Hands on bells, strong plank, row one, then the other. Wide feet. No hip sway. Light bells. A push-up between rows is optional and harder.'),
  e('SYS_MOV_MANMAKER', 'Man maker', 'Conditioning', 'Dumbbells', 'Full body', 'advanced',
    'Push-up, renegade rows, then a clean to thruster. A brutal complex.',
    'Write the exact standard. This is a finisher or a test, not a first class. Scale to a push-up + row + squat. Quality over speed.'),
  e('SYS_MOV_KB_PRESS', 'Kettlebell press', 'Push', 'Kettlebell', 'Delts, triceps, core', 'intermediate',
    'Strict press from the rack. The cleanest KB overhead.',
    'Quiet rack, ribs down, press to a locked arm by the ear. One arm. Bottoms-up is a harder cousin. Do not lean back into a standing incline.'),
  e('SYS_MOV_BU_PRESS', 'Bottoms-up kettlebell press', 'Push', 'Kettlebell', 'Shoulder stabilisers, core, grip', 'advanced',
    'Press with the bell upside down. Light, precise, humbling.',
    'Rack the bell upside down, press without letting it flop. Very light. A stability drill, not a strength max. The set ends when the bell wobbles over.'),
  e('SYS_MOV_WINDMILL', 'Kettlebell windmill', 'Core', 'Kettlebell', 'Obliques, hamstrings, shoulder', 'advanced',
    'Hinge and rotate under a locked-out bell. Mobility plus strength.',
    'Bell overhead, eyes on it, push the hip out and slide the free hand down the leg, then stand. Light. Teach without a bell. Not a class-wide default.'),
  e('SYS_MOV_KB_GOBLET_CLEAN', 'Kettlebell goblet clean', 'Olympic', 'Kettlebell', 'Hips, upper back', 'beginner',
    'Clean the bell to a goblet, not a rack. The first KB clean.',
    'Hike and snap, catch the horns at the chest. Easier than a rack clean. A teaching tool and a fine way to get into goblet squats.'),
  e('SYS_MOV_DEVIL_PRESS', 'Devil press', 'Conditioning', 'Dumbbells', 'Full body', 'advanced',
    'Burpee over or between bells into a double snatch / swing to overhead.',
    'Write the standard (snatch vs swing to overhead). This is a metcon piece. Light bells. A burpee + DB snatch each arm is the scale.'),
  e('SYS_MOV_FARMERS_HOLD', 'Farmer hold', 'Carry', 'Dumbbells or farmer handles', 'Grip, traps, core', 'beginner',
    'Pick up heavy bells and stand there. Grip and posture without the walk.',
    'Stand tall, pack the shoulders, hold 20–40 seconds. When the grip goes, set down with control. A valid set if the aisle is blocked.'),
];
