/**
 * Canonical NSNP-style approved foods seed (national template).
 * Cloned into each DBE/PEU agency catalogue so schools & SPs measure against it.
 * Agency edits remain on their agency_profile_id rows — live for all associates.
 */

export type NsnpSeedBrand = {
  name: string;
  slug: string;
  manufacturer: string;
  notes?: string;
};

export type NsnpSeedProduct = {
  brand_slug: string;
  category: string;
  name: string;
  pack_size: string;
  uom: string;
  energy_kcal?: number | null;
  protein_g?: number | null;
  notes?: string;
};

export const NSNP_SEED_BRANDS: NsnpSeedBrand[] = [
  { name: 'Ace', slug: 'ace', manufacturer: 'Tiger Brands', notes: 'Maize meal' },
  { name: 'Iwisa', slug: 'iwisa', manufacturer: 'Premier FMCG', notes: 'Maize meal' },
  {
    name: 'White Star',
    slug: 'white-star',
    manufacturer: 'Pioneer Foods',
    notes: 'Maize meal',
  },
  { name: 'SASKO', slug: 'sasko', manufacturer: 'Pioneer Foods', notes: 'Flour / bread' },
  { name: 'Sunfoil', slug: 'sunfoil', manufacturer: 'Willowton', notes: 'Cooking oil' },
  { name: 'Bokomo', slug: 'bokomo', manufacturer: 'Pioneer Foods', notes: 'Cereals' },
  { name: 'Rainbow', slug: 'rainbow', manufacturer: 'RCL Foods', notes: 'Protein' },
  {
    name: 'Lucky Star',
    slug: 'lucky-star',
    manufacturer: 'Oceana',
    notes: 'Canned fish',
  },
  {
    name: 'Tastic',
    slug: 'tastic',
    manufacturer: 'RCL Foods',
    notes: 'Rice',
  },
  {
    name: 'Spekko',
    slug: 'spekko',
    manufacturer: 'Tiger Brands',
    notes: 'Rice',
  },
  {
    name: 'Imana',
    slug: 'imana',
    manufacturer: 'Imana Foods',
    notes: 'Soup / soya',
  },
  {
    name: 'Knorrox',
    slug: 'knorrox',
    manufacturer: 'Unilever',
    notes: 'Stock / flavour',
  },
  {
    name: 'Generic Fortified',
    slug: 'generic-fortified',
    manufacturer: 'NSNP Generic',
    notes: 'Brand-neutral fortified commodities',
  },
  {
    name: 'Big Five Foods',
    slug: 'big-five-foods',
    manufacturer: 'Big Five Foods',
    notes: 'Programme-ready commodities',
  },
];

/** Comprehensive starter catalogue for school feeding measurement. */
export const NSNP_SEED_PRODUCTS: NsnpSeedProduct[] = [
  // Maize meal / staples
  {
    brand_slug: 'ace',
    category: 'maize_meal',
    name: 'Ace Super Maize Meal 12.5kg',
    pack_size: '12.5kg',
    uom: 'kg',
    energy_kcal: 350,
    protein_g: 8,
  },
  {
    brand_slug: 'ace',
    category: 'maize_meal',
    name: 'Ace Super Maize Meal 25kg',
    pack_size: '25kg',
    uom: 'kg',
    energy_kcal: 350,
    protein_g: 8,
  },
  {
    brand_slug: 'iwisa',
    category: 'maize_meal',
    name: 'Iwisa Maize Meal 12.5kg',
    pack_size: '12.5kg',
    uom: 'kg',
    energy_kcal: 350,
    protein_g: 8,
  },
  {
    brand_slug: 'iwisa',
    category: 'maize_meal',
    name: 'Iwisa Maize Meal 25kg',
    pack_size: '25kg',
    uom: 'kg',
    energy_kcal: 350,
    protein_g: 8,
  },
  {
    brand_slug: 'white-star',
    category: 'maize_meal',
    name: 'White Star Super Maize Meal 12.5kg',
    pack_size: '12.5kg',
    uom: 'kg',
    energy_kcal: 350,
    protein_g: 8,
  },
  {
    brand_slug: 'white-star',
    category: 'maize_meal',
    name: 'White Star Super Maize Meal 25kg',
    pack_size: '25kg',
    uom: 'kg',
    energy_kcal: 350,
    protein_g: 8,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'maize_meal',
    name: 'Fortified Super Maize Meal 12.5kg',
    pack_size: '12.5kg',
    uom: 'kg',
    energy_kcal: 350,
    protein_g: 8,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'samp',
    name: 'Samp (dried) 10kg',
    pack_size: '10kg',
    uom: 'kg',
    energy_kcal: 360,
    protein_g: 7,
  },

  // Rice
  {
    brand_slug: 'tastic',
    category: 'rice',
    name: 'Tastic Rice 10kg',
    pack_size: '10kg',
    uom: 'kg',
    energy_kcal: 360,
    protein_g: 7,
  },
  {
    brand_slug: 'spekko',
    category: 'rice',
    name: 'Spekko Rice 10kg',
    pack_size: '10kg',
    uom: 'kg',
    energy_kcal: 360,
    protein_g: 7,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'rice',
    name: 'Fortified Rice 10kg',
    pack_size: '10kg',
    uom: 'kg',
    energy_kcal: 360,
    protein_g: 7,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'rice',
    name: 'Fortified Rice 25kg',
    pack_size: '25kg',
    uom: 'kg',
    energy_kcal: 360,
    protein_g: 7,
  },

  // Flour / bread-related
  {
    brand_slug: 'sasko',
    category: 'flour',
    name: 'SASKO Cake Wheat Flour 10kg',
    pack_size: '10kg',
    uom: 'kg',
    energy_kcal: 364,
    protein_g: 10,
  },
  {
    brand_slug: 'sasko',
    category: 'flour',
    name: 'SASKO Bread Wheat Flour 12.5kg',
    pack_size: '12.5kg',
    uom: 'kg',
    energy_kcal: 364,
    protein_g: 12,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'flour',
    name: 'Fortified Cake Flour 10kg',
    pack_size: '10kg',
    uom: 'kg',
    energy_kcal: 364,
    protein_g: 10,
  },

  // Cereals / porridge
  {
    brand_slug: 'bokomo',
    category: 'cereal',
    name: 'Bokomo Oats 1kg',
    pack_size: '1kg',
    uom: 'kg',
    energy_kcal: 379,
    protein_g: 13,
  },
  {
    brand_slug: 'bokomo',
    category: 'cereal',
    name: 'Bokomo Oats 5kg',
    pack_size: '5kg',
    uom: 'kg',
    energy_kcal: 379,
    protein_g: 13,
  },
  {
    brand_slug: 'big-five-foods',
    category: 'porridge',
    name: 'Fortified Porridge',
    pack_size: 'bulk',
    uom: 'kg',
    energy_kcal: 380,
    protein_g: 12,
    notes: 'NSNP fortified porridge blend',
  },
  {
    brand_slug: 'generic-fortified',
    category: 'porridge',
    name: 'Instant Fortified Maize Porridge 5kg',
    pack_size: '5kg',
    uom: 'kg',
    energy_kcal: 370,
    protein_g: 9,
  },

  // Legumes
  {
    brand_slug: 'generic-fortified',
    category: 'beans',
    name: 'Fortified Sugar Beans 5kg',
    pack_size: '5kg',
    uom: 'kg',
    energy_kcal: 333,
    protein_g: 23,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'beans',
    name: 'Sugar Beans 10kg',
    pack_size: '10kg',
    uom: 'kg',
    energy_kcal: 333,
    protein_g: 23,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'lentils',
    name: 'Red Lentils 5kg',
    pack_size: '5kg',
    uom: 'kg',
    energy_kcal: 352,
    protein_g: 25,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'peas',
    name: 'Split Peas 5kg',
    pack_size: '5kg',
    uom: 'kg',
    energy_kcal: 341,
    protein_g: 25,
  },
  {
    brand_slug: 'big-five-foods',
    category: 'soya',
    name: 'Soya Mince',
    pack_size: 'bulk',
    uom: 'kg',
    energy_kcal: 330,
    protein_g: 50,
  },
  {
    brand_slug: 'imana',
    category: 'soya',
    name: 'Imana Soya Mince 1kg',
    pack_size: '1kg',
    uom: 'kg',
    energy_kcal: 330,
    protein_g: 48,
  },

  // Protein animal
  {
    brand_slug: 'rainbow',
    category: 'protein',
    name: 'Rainbow Chicken IQF 2kg',
    pack_size: '2kg',
    uom: 'kg',
    energy_kcal: 165,
    protein_g: 31,
  },
  {
    brand_slug: 'rainbow',
    category: 'protein',
    name: 'Rainbow Chicken IQF 5kg',
    pack_size: '5kg',
    uom: 'kg',
    energy_kcal: 165,
    protein_g: 31,
  },
  {
    brand_slug: 'lucky-star',
    category: 'protein',
    name: 'Lucky Star Pilchards in Tomato 400g',
    pack_size: '400g',
    uom: 'tin',
    energy_kcal: 180,
    protein_g: 18,
  },
  {
    brand_slug: 'lucky-star',
    category: 'protein',
    name: 'Lucky Star Pilchards in Brine 400g',
    pack_size: '400g',
    uom: 'tin',
    energy_kcal: 170,
    protein_g: 19,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'protein',
    name: 'Eggs (tray 30)',
    pack_size: '30',
    uom: 'each',
    energy_kcal: 143,
    protein_g: 13,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'protein',
    name: 'Full cream milk powder 1kg',
    pack_size: '1kg',
    uom: 'kg',
    energy_kcal: 496,
    protein_g: 26,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'protein',
    name: 'UHT Full cream milk 1L',
    pack_size: '1L',
    uom: 'L',
    energy_kcal: 64,
    protein_g: 3.3,
  },

  // Oils & fats
  {
    brand_slug: 'sunfoil',
    category: 'oil',
    name: 'Sunfoil Cooking Oil 5L',
    pack_size: '5L',
    uom: 'L',
    energy_kcal: 884,
    protein_g: 0,
  },
  {
    brand_slug: 'sunfoil',
    category: 'oil',
    name: 'Sunfoil Cooking Oil 20L',
    pack_size: '20L',
    uom: 'L',
    energy_kcal: 884,
    protein_g: 0,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'oil',
    name: 'Fortified Cooking Oil 5L',
    pack_size: '5L',
    uom: 'L',
    energy_kcal: 884,
    protein_g: 0,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'spread',
    name: 'Peanut butter 400g',
    pack_size: '400g',
    uom: 'jar',
    energy_kcal: 588,
    protein_g: 25,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'spread',
    name: 'Peanut butter 5kg',
    pack_size: '5kg',
    uom: 'kg',
    energy_kcal: 588,
    protein_g: 25,
  },

  // Vegetables & fruit
  {
    brand_slug: 'generic-fortified',
    category: 'vegetables',
    name: 'Frozen Mixed Vegetables 1kg',
    pack_size: '1kg',
    uom: 'kg',
    energy_kcal: 65,
    protein_g: 2.5,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'vegetables',
    name: 'Frozen Mixed Vegetables 2.5kg',
    pack_size: '2.5kg',
    uom: 'kg',
    energy_kcal: 65,
    protein_g: 2.5,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'vegetables',
    name: 'Canned Mixed Vegetables 3kg',
    pack_size: '3kg',
    uom: 'tin',
    energy_kcal: 50,
    protein_g: 2,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'vegetables',
    name: 'Fresh cabbage (head)',
    pack_size: 'each',
    uom: 'each',
    energy_kcal: 25,
    protein_g: 1.3,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'vegetables',
    name: 'Fresh carrots 5kg',
    pack_size: '5kg',
    uom: 'kg',
    energy_kcal: 41,
    protein_g: 0.9,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'vegetables',
    name: 'Onions 5kg',
    pack_size: '5kg',
    uom: 'kg',
    energy_kcal: 40,
    protein_g: 1.1,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'vegetables',
    name: 'Potatoes 10kg',
    pack_size: '10kg',
    uom: 'kg',
    energy_kcal: 77,
    protein_g: 2,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'fruit',
    name: 'Seasonal fruit (apples) 5kg',
    pack_size: '5kg',
    uom: 'kg',
    energy_kcal: 52,
    protein_g: 0.3,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'fruit',
    name: 'Seasonal fruit (bananas) 5kg',
    pack_size: '5kg',
    uom: 'kg',
    energy_kcal: 89,
    protein_g: 1.1,
  },

  // Seasoning / condiments
  {
    brand_slug: 'generic-fortified',
    category: 'salt',
    name: 'Iodised table salt 1kg',
    pack_size: '1kg',
    uom: 'kg',
    energy_kcal: 0,
    protein_g: 0,
  },
  {
    brand_slug: 'knorrox',
    category: 'stock',
    name: 'Knorrox Stock Cubes (box)',
    pack_size: 'box',
    uom: 'box',
    energy_kcal: 20,
    protein_g: 1,
  },
  {
    brand_slug: 'imana',
    category: 'soup',
    name: 'Imana Soup Mix 1kg',
    pack_size: '1kg',
    uom: 'kg',
    energy_kcal: 320,
    protein_g: 12,
  },
  {
    brand_slug: 'generic-fortified',
    category: 'sugar',
    name: 'White sugar 2.5kg',
    pack_size: '2.5kg',
    uom: 'kg',
    energy_kcal: 387,
    protein_g: 0,
  },

  // Ready meals / programme packs
  {
    brand_slug: 'big-five-foods',
    category: 'ready_meal',
    name: 'OnePot',
    pack_size: 'bulk',
    uom: 'kg',
    energy_kcal: 400,
    protein_g: 15,
    notes: 'Complete meal solution for NSNP',
  },
];
