/**
 * Simple customer AR statement PDF (open invoices).
 */
import PDFDocument from 'pdfkit';

export type StatementLine = {
  invoiceNumber: string;
  status: string;
  dueDate: string | null;
  promiseDate: string | null;
  balance: number;
  currency: string;
  brokenPromise?: boolean;
};

export type StatementInput = {
  sellerName: string;
  customerName: string;
  asOf: string;
  lines: StatementLine[];
  openTotal: number;
  currency: string;
};

export async function buildArStatementPdf(
  input: StatementInput
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (c) => chunks.push(c as Buffer));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc
      .fontSize(18)
      .fillColor('#0f172a')
      .text('Account statement — open invoices', { continued: false });
    doc.moveDown(0.3);
    doc
      .fontSize(10)
      .fillColor('#64748b')
      .text(`${input.sellerName} · as of ${input.asOf}`);
    doc.moveDown(0.8);
    doc
      .fontSize(12)
      .fillColor('#0f172a')
      .text(`Customer: ${input.customerName}`);
    doc
      .fontSize(11)
      .text(
        `Open balance: ${input.currency} ${input.openTotal.toLocaleString(
          undefined,
          { maximumFractionDigits: 2 }
        )}`
      );
    doc.moveDown(0.8);

    doc.fontSize(9).fillColor('#94a3b8').text('Invoice', 48, doc.y, {
      continued: true,
      width: 120,
    });
    doc.text('Status', 170, doc.y, { continued: true, width: 70 });
    doc.text('Due', 250, doc.y, { continued: true, width: 70 });
    doc.text('Promise', 330, doc.y, { continued: true, width: 70 });
    doc.text('Balance', 420, doc.y, { width: 100, align: 'right' });
    doc
      .moveTo(48, doc.y + 4)
      .lineTo(547, doc.y + 4)
      .strokeColor('#e2e8f0')
      .stroke();
    doc.moveDown(0.6);

    for (const line of input.lines) {
      if (doc.y > 720) doc.addPage();
      const y = doc.y;
      doc
        .fontSize(9)
        .fillColor(line.brokenPromise ? '#9f1239' : '#0f172a')
        .text(line.invoiceNumber, 48, y, { width: 120 });
      doc.fillColor('#334155').text(line.status, 170, y, { width: 70 });
      doc.text(line.dueDate || '—', 250, y, { width: 70 });
      doc.text(
        line.promiseDate
          ? `${line.promiseDate}${line.brokenPromise ? ' !' : ''}`
          : '—',
        330,
        y,
        { width: 70 }
      );
      doc.text(
        `${line.currency} ${line.balance.toLocaleString(undefined, {
          maximumFractionDigits: 2,
        })}`,
        420,
        y,
        { width: 100, align: 'right' }
      );
      doc.moveDown(0.55);
    }

    doc.moveDown(1);
    doc
      .fontSize(8)
      .fillColor('#94a3b8')
      .text(
        'Generated by SupplierAdvisor® · payment refs and promises recorded on invoices',
        { align: 'left' }
      );

    doc.end();
  });
}
